# Generated by Django 2.2 on 2020-03-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='group', max_length=50)),
                ('members', models.ManyToManyField(to='blog.User')),
            ],
        ),
    ]
