# Generated by Django 2.2 on 2020-03-15 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
